= Feature docs

what I like about feature docs...

Explain RTFM-Industries... 

== Conceptual feature docs

=== RTFM-Industries documentation dashboards (XHTML)

View feature documentation for the fictional RTFM-Industries Documentation Dashboard feature.
The following link:../../overview/#_topic_typing[concept documentation] introduces RTFM-Industries Documentation Dashboards, a splendid feature that helps tech writers do their jobs more effectively.

[,html]
----
include::/examples/documentation-dashboards-overview.html[]
----

== Task-oriented feature docs

=== Create a new documentation dashboard (XHTML)

The following link:../../overview/#_topic_typing[task] instructs users how to create a new Documentation Dashboard that evaluates the effectiveness of published documentation.

[,html]
----
include::/examples/documentation-dashboards-create.html[]
----

=== Invoicing setup page (XHTML)

[,html]
----
include::./examples/invoicing-setup.html[]
----

=== Match a supplier invoice (XHTML)

[,html]
----
include::./examples/match-invoice.html[]
----

=== Configure notifications (AsciiDoc) 

[,asciidoc]
----
include::./examples/notification-config.adoc[lines=4..-1]
----

