= N. Parker Jones
:navtitle: Welcome

Hi, I'm Parker! Welcome to my tech writing portfolio. 

I'm an experienced tech writer who's worked in the Financial and Facility Management industries for over six years. 

As a self-taught Linux power user, I know the importance of quality documentation and how painful it is to be stuck with lacking instructions. "User empathy" is an overused buzzword, but let's just say I've suffered through enough poorly documented open source software for it to dramatically inform my tech writing approach.  

== Docs-as-code

I prefer to treat my docs like source code. Using modern software development processes and tooling makes it possible to produce modular, reviewed, and accessible documentation at scale. 

== Agile methodology

From years of implementing Agile, I've learned the value of proper ticket management, clear acceptance criteria, tight feedback loops with SMEs/shareholders, and periodic reflection for how to improve.

== Simple language

I believe it's harder to write a single clear sentence than a paragraph of jumbled jargon. The challenge of tech writing is to translate the complexity of software into manageable concepts and tasks.

== Tooling

todo...

== The perils of technical writing 

I enjoy working in the middle of this spectrum, preferably not too far to the right!
