= N. Parker Jones

Experienced tech writer (6+ years) with an emphasis on Agile methodology, docs-as-code processes, and
clear communication over jumbled jargon.

.Skills
[cols="2",grid="none",frame="none",table-stripes="odd"]
|===
| - MadCap Flare
| - Jira & Confluence
| - Git/GitHub
| - Agile methodology
| - Snagit
| - Editing
| - Hugo
| - Antora
|===

== Experience

=== Corcentric, LLC (remote)
_Technical Writer_, March 2022 - March 2023

* Finance-specific (invoicing, procurement, order to cash, procure to pay) with MadCap Flare
* Transitioned two products from Microsoft Word to MadCap Flare
* Coordinated release scheduling for three products with independent release schedules
* Implemented Git branching and style guide verification with Vale
* Localized content for multi-language translation support

=== FM:Systems Group, LLC (remote)
_Technical Writer, team lead_, June 2016 - August 2021

* Spearheaded the transition of docs from MS Word to MadCap Flare and Hugo for HTML and PDF outputs
* Deployed online documentation for the first time in company's history
* Implemented Git processes (branching, pull requests, merging, release tagging) for the technical writing team source code
* Implemented review standards and style guide verification with Mad Quality and Vale plugins
* Developed on-boarding and training materials for new tech writers in Confluence

=== Cisco Systems Inc.
_Technical Writer_
August 2015 - May 2016

* Collaborated with subject-matter experts across six departments to product internal
documentation
* Formalized procedures and protocols to increase efficiency and confidence in meeting deadlines

== Education

=== Master of Arts, English
_University of North Carolina at Wilmington_ | Wilmington, NC 
2015, summa cum laude

=== Bachelor of Arts, English
_University of North Carolina at Wilmington_ | Wilmington, NC 
2011

== Certifications & Awards

* Poynter ACES Certificate in Editing, 2021
* Eagle Scout, Boy Scouts of America, 2007
