theme = 'dark-theme-editor'

# Theme parameters - copied from /themes/dark-editor-theme/hugo.toml
# override as needed
[params]

    # Parameters applied in HTML <head>
    [params.site]
        # Website ICON
        faviconUrl = ""

        # Do you have any CSS in local? List them in an array.
        # They should be placed inside "/assets" dir.
        # Please list your files relative to the /assets directory.
        # Glob pattern is acceptable
        # If only a few pages need the extra style files, list them in the page metadata.
        localCss = []

        # Do you need to add any external CSS? List their URL in an array.
        # If only a few pages need the extra style files, list them in the page metadata.
        # These URLs will be inserted into <link> tags directly without any check.
        externalCss = []

        # Like the one above, but this will download a local copy and combine it with 
        # other CSS files into a single file while in production mode.
        externalCssDownload = []

        # Do you have any script in local? List them in an array.
        # They should be placed inside "/assets" dir.
        # Please list your files relative to the /assets directory.
        # Glob pattern is acceptable
        # If only a few pages need the extra script files, list them in the page metadata.
        localJs = []

        # Do you have any external Script need to add on? List their URL in an array.
        # If only a few pages need the extra script files, list them in the page metadata.
        # These URLs will be inserted into <script> tags directly without any check.
        externalJs = []

        # Like the one above, but this will download a local copy and combine it with 
        # other JS files into a single file while in production mode.
        externalJsDownload = []

    # Customized info shown in header of the page
    [params.header]
        # Website title for header banner.
        title = "technicallyawriter"

        # Subtitle for this site, used in homepage only
        subtitle = "Welcome to my tech writing portfolio!"

        # Config about your's site logo, remove this item to hide the logo
        [params.header.logo]
            # Where is your site's URL
            imgUrl = ""

            # If the logo is clickable, where should it be linked?
            # In default, it will linked to the homepage of the site.
            logoLink = ""

    # Customized info shown in footer of the page
    [params.footer]
        copyrightStr = "No Rights Reserved"

        # Should show the counter in the footer or not
        # In the home page, it will show the numbers of all pages
        # In the sections pages, it will show the numbers of pages within the section
        # In the taxonomy pages, it will show the numbers of pages belong to the taxonomy.
        # In the regular content pages, it will show the word count.
        counter = true

        # Should show the language of the page or not
        language = true

        # Should show the hugo version or not
        hugoVersion = true

        # Should show the theme info or not
        theme = true

        # Should show the edited time of the page or not
        modifiedTime = true

        # Refer to page https://gohugo.io/functions/format/ for more detail.
        # Below is the default format, please do not remove it, unless you set `false` in `modifiedTime` field.
        dateFormat = "Jan 02 2006 15:04:05"

        # Should show the current git HEAD hash or not
        # To make this show up correctly, please follow the prerequisites in page
        # https://gohugo.io/variables/git/
        gitHash = true

        # Social link in the footer, listed items are supported, delete unwanted items to hide it.
        [params.footer.socialLink]
            github = "https://github.com/technicallyawriter"
            email = "npjones_techwriter@proton.me"
            linkedin = "https://www.linkedin.com/in/parker-j-151391223/"

    [params.globalFrontmatter]
        author = "Parker Jones"
        
        # Website description for RSS and SEO. Theme will generate a <meta> tag for this item
        description = "Tech writing portfolio"

        # Website keywords. Theme will generate a <meta> tag for this item.
        keywords = "portfolio,technical writing,hugo,madcap flare"

    # Parameters applied in the homepage only
    [params.homePage]
        siteLongDescription = "TODO..."
        siteLongDescriptionTitle = "About me"
        showRecentPostsBlock = false

    # Paramater applied in the single page
    # These values could be overwritten by the frontmatter in the single page.
    [params.page]
        # Should include Table of Content in front of the page or not.
        includeToc = true
        showAuthor = true
        showDate = true
        dateFormat = "2006.01.02"
        showTimeToRead = true
        showBreadcrumb = true
        # Should show the "copy" button in the codeblock or not.
        codeBlockCopible = true

# security configuration to allow third-party app execution (required for asciidoctor)
[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG)$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']
  [security.goTemplates]
    allowActionJSTmpl = false
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

