= Feature docs

Introduce fictional company, RTFM-Industries. Tailor all samples to RTFM-Industries (update intros).

== Documentation dashboards overview

View feature documentation for the fictional RTFM-Industries Documentation Dashboard feature.
The following link:../../overview/#_topic_typing[concept documentation] introduces RTFM-Industries Documentation Dashboards, a splendid feature that helps tech writers do their jobs more effectively.

.Documentation Dashboards Overview
[source,html]
----
include::example$documentation-dashboards-overview.html[]
----


== Create a new documentation dashboard

The following link:../../overview/#_topic_typing[task] instructs users how to create a new Documentation Dashboard that evaluates the effectiveness of published documentation.

.Create a new documentation dashboard
[source,html]
----
include::example$documentation-dashboards-create.html[]
----

== Invoicing setup

.Invoicing setup for documentation dashboards
[source,html]
----
include::example$invoicing-setup.html[]
----

== Match an invoice 

.Match an invoice
[source,html]
----
include::example$match-invoice.html[]
----

== Configure notifications (AsciiDoc) 

[,asciidoc]
----
include::example$notification-config.adoc[lines=4..-1]
----
