:experimental:

= MadCap Flare

A majority of my tech writing experience is in MadCap Flare. Single-sourcing content for multiple outputs with conditional text, targets, and TOCs is like riding a bike (a somewhat heavy bike that crashes if you change gears too quickly). I poke fun at Flare because I've worked within it for so long. 

Since it's proprietary, it's Flare's way or the highway, and its lacking extensibility feels like a limitation after years of use. Still, it's a solid tool that I'm more than comfortable in.

Perhaps most importantly, Flare is a fully featured product with a friendly UI. I've found this makes the learning curve less steep, which means you get more help from other tech writers!

== Importing from Microsoft Word

Flare is great for transitioning from .docx files to online docs. The efficiency by which you can import Word files, build a TOC, and publish an HTML target is worth the price tag, in my experience. Sure you can write a Pandoc script that walks directories and transforms .DOCX files to .XHTML, but with the organizational cost of writing and maintaining this workflow, I feel Flare has a competitive advantage--not to mention the stability of a tried-and-tested product. 

I've led transitions from Word to Flare at two different organizations, so the process feels like a well-oiled machine at this point. Map Word to Flare styles, remove all of Word's messy inline styling, and you've quickly produced bare-bones XHTML content you can polish further if you wish.

== Global Project Linking

Flare's emphasis on content re-use means creating scalable projects with the link:https://help.madcapsoftware.com/flare2023r2/Content/Flare/Global-Project-Linking/Global-Project-Linking.htm[Global Project Linking^] technique. 
I've lead efforts at two organizations in restructuring Flare content to use this approach. Put simply, all shared assets go in a parent-level project. Then, all projects that wish to reuse this content import the shared assets. To update these shared assets, edit them in the parent-level project and re-import from all the child projects.

.An example of Global Project Linking structure
[source,ascii]
----
shared.flprj
├── project1.flprj
├── project2.flprj
└── project3.flprj
----

NOTE: This is a conceptual hierarchy. The projects don't need to be literally nested within the parent project.

== Snippets

how I prefer to organize...

menu:Resources[Snippets > Product Area > Snippet.flsnp]. You can also just nest a "snippets" folder within each Product Area in the main content editor. It's really a choice of preference.

== Global variables

Managing global variables is simple with Flare. They're automatically included, so you don't need to explicitly `include::attributes.adoc[]` (for example) like have to in AsciiDocs. This is a small consideration, but small things add up and it's nice when Flare handles it for me.

== Conditional text

Flare's conditional text is managed similar to variables. The conditions you wish to exclude are stored logically in a simple table with label, definition, and a include/exclude filter columns for each row. 

Someone common examples are to use a `PrintOnly` condition to exclude content from online targets, or an `AdminOnly` condition to hide admininstrator-level content from general use docs. You can apply conditions to an entire file to exclude it from a specific target, or you can highlight in-line text to filter accordingly. 

== PDF styling

The fact that you can use CSS for PDF styling in Flare has saved me many headaches. Again, Flare excels at single sourcing and this includes styling PDFs. Transforming XML to PDF is inherently a messy venture, so maintaining a syntax I'm familiar with means one less unfamiliar link in the chain. You can create a dedicated `Print.css` file that imports styling you want to include from your `Main.css` or you can use media tags (`@media print`) at the bottom of your `Main.css` file.

As a comparison, I think Flare's PDF styling approach is much simpler compared to the .YAML theming files used in `asciidoctor-pdf`, for example.
