---
title: "Feature docs"
date: 2023-11-02T12:15:26-04:00
draft: true
weight: -15
---
:toc:

== Feature docs
what I like about feature docs...

Explain RTFM-Industries... 

== Conceptual feature docs
=== RTFM-Industries documentation dashboards (XHTML)

View feature documentation for the fictional RTFM-Industries Documentation Dashboard feature.
The following link:../../overview/#_topic_typing[concept documentation] introduces RTFM-Industries Documentation Dashboards, a splendid feature that helps tech writers do their jobs more effectively.

[,html]
----
include::./content/writingsamples/source/documentation-dashboards-overview.html[]
----

== Task-oriented feature docs

=== Create a new documentation dashboard (XHTML)

The following link:../../overview/#_topic_typing[task] instructs users how to create a new Documentation Dashboard that evaluates the effectiveness of published documentation.

[,html]
----
include::./content/writingsamples/source/documentation-dashboards-create.html[]
----

=== Invoicing setup page (XHTML)

[,html]
----
include::./content/writingsamples/source/invoicing-setup.html[]
----

=== Match a supplier invoice (XHTML)

[,html]
----
include::./content/writingsamples/source/match-invoice.html[]
----

=== Configure notifications (AsciiDoc) 

[,asciidoc]
----
include::./content/writingsamples/source/notification-config.adoc[lines=4..-1]
----

